---
- hosts: localhost
  become: yes


  vars_files:
    - var.yml

  pre_tasks:
    - name: "Install packages"
      yum: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-server

    - name: Install python2-pip
      yum:
        name: python2-pip
        state: present

    - name: "Install Python packages"
      pip:
            name: "{{ item }}"
            state: present

      with_items:
        - psycopg2-binary

  tasks:
    - name: "Find out if PostgreSQL is initialized"
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: "Initialize PostgreSQL"
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql

    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        #role_attr_flags: CREATEDB,NOSUPERUSER
      become_user: postgres
    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: yes
        privs: all
      become_user: postgres

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: local
        databases: "{{ db_name }}"
        method: md5
        src: 127.0.0.1/32
        users: "{{ db_user }}"
        create: true

      become_user: postgres
      notify: restart postgres



  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted



